### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [fujiwarat/input-pad#8]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by fujiwarat** [comment]
> * [mandatory] which branch is your development branch?

master

> * [mandatory] have you merged latest translation from Zanata and locked the project?

Yes

> * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

It should be same with the license in the ibus SPEC file in Fedora.

> * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

The comment lines for MSGID should be informed to translators.

> * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

No. Currently null comment lines are deleted in Weblate and I always revert it and I will file the RFE later.
If the copyright header "# Copyright (C) 2010-20** Takao Fujiwara" could be replaced with "# Copyright (C) 2010-2020 Takao Fujiwara" in the pull request, it would be great.

> * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No. If the first line of the POT file "# Source translations for input-pad" could be replaced with the new language, e.g. "# German translations for input-pad"  automatically, it would be great.

**Comment by Jibec** [comment]
done: https://translate.stg.fedoraproject.org/projects/input-pad/
you are now admin of this project

Weblate will update LINGUAS file
Weblate will update all po file each time you change the pot file, you don't need to update it
Git squash is done by Author

**Comment by fujiwarat** [comment]
Thank you for the quick implementation.

> Weblate will update LINGUAS file

I understood you mean this works in case the Git repository has a POT file.
An IBus pull request didn't update LINGUAS; https://github.com/ibus/ibus/pull/2169 and I guess the reason was that I didn't push the POT file in Git.
Now I push an IBus POT file in Git and hope this works in IBus too.

**Comment by Jibec** [comment]
Yes, I'll fix that today
